blank_issues_enabled: true
contact_links:
  - name: Security vulnerability reporting
    url: https://github.com/aliziodev/payid/blob/main/SECURITY.md
    about: Please report vulnerabilities privately following SECURITY.md
